spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: jackpotter
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false

espn:
  api:
    base-url: https://site.api.espn.com/apis/site/v2/sports/football
    scoreboard:
      limit: 1000