spring:

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false

espn:
  api:
    base-url: https://site.api.espn.com/apis/site/v2/sports/football
    scoreboard:
      limit: 1000